import archiver from "archiver";
import { PassThrough } from "stream";
import { getDb } from "../db";
import { products, projects, games, vocabularyItems } from "../../drizzle/schema";
import { eq, and } from "drizzle-orm";

export interface ZipBundleOptions {
  projectId: number;
  userId: number;
  includeProducts?: boolean;
  includeGames?: boolean;
  includeVocabulary?: boolean;
}

export async function generateProjectZipBundle(options: ZipBundleOptions): Promise<{ stream: PassThrough; filename: string }> {
  const { projectId, userId, includeProducts = true, includeGames = true, includeVocabulary = true } = options;

  const db = await getDb();
  if (!db) throw new Error("Database not available");

  // Verify ownership
  const [project] = await db
    .select()
    .from(projects)
    .where(and(eq(projects.id, projectId), eq(projects.userId, userId)));

  if (!project) throw new Error("Project not found or access denied");

  const archive = archiver("zip", { zlib: { level: 9 } });
  const passThrough = new PassThrough();
  archive.pipe(passThrough);

  const safeTitle = (project.title || "EduFactory_Project")
    .replace(/[^a-zA-Z0-9_\-\s]/g, "")
    .replace(/\s+/g, "_")
    .substring(0, 50);

  const filename = `${safeTitle}_EduBundle.zip`;

  // ─── README ───────────────────────────────────────────────────────────────
  const readmeContent = generateReadme(project);
  archive.append(readmeContent, { name: "README.md" });

  // ─── PRODUCTS ─────────────────────────────────────────────────────────────
  if (includeProducts) {
    const productList = await db
      .select()
      .from(products)
      .where(eq(products.projectId, projectId));

    for (const product of productList) {
      const content = generateProductMarkdown(product);
      const productFolder = `products/${product.type}/`;
      const productFilename = `${productFolder}${product.type}_${product.id}.md`;
      archive.append(content, { name: productFilename });

      // Also generate a plain text version
      const plainText = generateProductPlainText(product);
      archive.append(plainText, { name: `${productFolder}${product.type}_${product.id}.txt` });
    }

    // Products index
    const indexContent = generateProductsIndex(productList);
    archive.append(indexContent, { name: "products/INDEX.md" });
  }

  // ─── VOCABULARY ───────────────────────────────────────────────────────────
  if (includeVocabulary) {
    const vocab = await db
      .select()
      .from(vocabularyItems)
      .where(eq(vocabularyItems.projectId, projectId));

    if (vocab.length > 0) {
      const vocabCsv = generateVocabCSV(vocab);
      archive.append(vocabCsv, { name: "vocabulary/vocabulary_list.csv" });

      const vocabAnki = generateAnkiDeck(vocab);
      archive.append(vocabAnki, { name: "vocabulary/anki_import.txt" });

      const vocabMarkdown = generateVocabMarkdown(vocab);
      archive.append(vocabMarkdown, { name: "vocabulary/vocabulary_reference.md" });
    }
  }

  // ─── GAMES ────────────────────────────────────────────────────────────────
  if (includeGames) {
    const gameList = await db
      .select()
      .from(games)
      .where(eq(games.projectId, projectId));

    if (gameList.length > 0) {
      const gamesIndex = generateGamesIndex(gameList);
      archive.append(gamesIndex, { name: "games/GAMES_LINKS.md" });
    }
  }

  // ─── MARKETPLACE CARD ─────────────────────────────────────────────────────
  const marketplaceCard = generateMarketplaceCard(project);
  archive.append(marketplaceCard, { name: "marketplace/product_listing.md" });

  const etsy = generateEtsyListing(project);
  archive.append(etsy, { name: "marketplace/etsy_listing.txt" });

  const tpt = generateTPTDescription(project);
  archive.append(tpt, { name: "marketplace/tpt_description.txt" });

  archive.finalize();

  return { stream: passThrough, filename };
}

// ─── GENERATORS ──────────────────────────────────────────────────────────────

function generateReadme(project: Record<string, unknown>): string {
  return `# ${project.title || "English Teaching Pack"}

**Generated by EduFactory** — AI-powered digital product factory for English teachers

## About This Bundle

- **Topic:** ${project.title || "N/A"}
- **CEFR Level:** ${project.cefrLevel || "B1"}
- **Source Type:** ${project.sourceType || "YouTube"}
- **Generated:** ${new Date().toLocaleDateString("en-GB", { year: "numeric", month: "long", day: "numeric" })}

## Bundle Contents

\`\`\`
📁 products/         — All educational products (Markdown + TXT)
📁 vocabulary/       — Vocabulary list (CSV + Anki import + Markdown)
📁 games/            — Interactive game links and instructions
📁 marketplace/      — Ready-to-use product listings (Etsy, TPT, Gumroad)
\`\`\`

## How to Use

1. **Print & Use** — Open any .md or .txt file in your preferred editor
2. **Canva** — Import content into Canva templates for professional designs
3. **Sell** — Use the marketplace/ folder for ready-made product descriptions
4. **Games** — Share game links with students (no login required)

---
*Generated with ❤️ by EduFactory — Turn any content into a complete lesson ecosystem*
`;
}

function generateProductMarkdown(product: Record<string, unknown>): string {
  let content: Record<string, unknown> = {};
  try {
    content = typeof product.content === "string" ? JSON.parse(product.content) : (product.content as Record<string, unknown>) || {};
  } catch {
    content = {};
  }

  const lines: string[] = [
    `# ${product.title || product.type}`,
    ``,
    `**Type:** ${product.type}`,
    `**Status:** ${product.status}`,
    ``,
    `---`,
    ``,
  ];

  // Render content based on type
  if (content.instructions) lines.push(`## Instructions\n\n${content.instructions}\n`);
  if (content.objectives) lines.push(`## Learning Objectives\n\n${Array.isArray(content.objectives) ? content.objectives.map((o: unknown) => `- ${o}`).join("\n") : content.objectives}\n`);
  if (content.vocabulary) lines.push(`## Vocabulary\n\n${Array.isArray(content.vocabulary) ? content.vocabulary.map((v: unknown) => typeof v === "object" ? `- **${(v as Record<string, unknown>).word}** — ${(v as Record<string, unknown>).definition}` : `- ${v}`).join("\n") : content.vocabulary}\n`);
  if (content.exercises) lines.push(`## Exercises\n\n${Array.isArray(content.exercises) ? content.exercises.map((e: unknown, i: number) => `### Exercise ${i + 1}\n${typeof e === "object" ? JSON.stringify(e, null, 2) : e}`).join("\n\n") : content.exercises}\n`);
  if (content.questions) lines.push(`## Questions\n\n${Array.isArray(content.questions) ? content.questions.map((q: unknown, i: number) => `${i + 1}. ${typeof q === "object" ? (q as Record<string, unknown>).question || JSON.stringify(q) : q}`).join("\n") : content.questions}\n`);
  if (content.answers) lines.push(`## Answer Key\n\n${Array.isArray(content.answers) ? content.answers.map((a: unknown, i: number) => `${i + 1}. ${a}`).join("\n") : content.answers}\n`);
  if (content.teacherNotes) lines.push(`## Teacher Notes\n\n${content.teacherNotes}\n`);
  if (content.timeRequired) lines.push(`**Estimated Time:** ${content.timeRequired}\n`);

  // Fallback: dump all content
  const knownKeys = ["instructions", "objectives", "vocabulary", "exercises", "questions", "answers", "teacherNotes", "timeRequired"];
  for (const [key, value] of Object.entries(content)) {
    if (!knownKeys.includes(key) && value) {
      lines.push(`## ${key.charAt(0).toUpperCase() + key.slice(1)}\n\n${typeof value === "object" ? JSON.stringify(value, null, 2) : value}\n`);
    }
  }

  return lines.join("\n");
}

function generateProductPlainText(product: Record<string, unknown>): string {
  let content: Record<string, unknown> = {};
  try {
    content = typeof product.content === "string" ? JSON.parse(product.content) : (product.content as Record<string, unknown>) || {};
  } catch {
    content = {};
  }
  return `${product.title || product.type}\n${"=".repeat(60)}\n\n${JSON.stringify(content, null, 2)}`;
}

function generateProductsIndex(productList: Record<string, unknown>[]): string {
  const lines = ["# Products Index\n", `Total: ${productList.length} products\n`, "| # | Type | Title | Status |", "|---|------|-------|--------|"];
  productList.forEach((p, i) => {
    lines.push(`| ${i + 1} | ${p.type} | ${p.title || "—"} | ${p.status} |`);
  });
  return lines.join("\n");
}

function generateVocabCSV(vocab: Record<string, unknown>[]): string {
  const header = "Word,Part of Speech,Definition,Example Sentence,Polish Translation,CEFR Level";
  const rows = vocab.map((v) =>
    [v.word, v.partOfSpeech, v.definition, v.exampleSentence, v.polishTranslation, v.cefrLevel]
      .map((cell) => `"${String(cell || "").replace(/"/g, '""')}"`)
      .join(",")
  );
  return [header, ...rows].join("\n");
}

function generateAnkiDeck(vocab: Record<string, unknown>[]): string {
  const header = "#separator:tab\n#html:false\n#notetype:Basic\n";
  const rows = vocab.map((v) => `${v.word}\t${v.definition} | Example: ${v.exampleSentence || ""}`);
  return header + rows.join("\n");
}

function generateVocabMarkdown(vocab: Record<string, unknown>[]): string {
  const lines = ["# Vocabulary Reference\n", `${vocab.length} words\n`];
  for (const v of vocab) {
    lines.push(`## ${v.word} *(${v.partOfSpeech || "n/a"})*`);
    lines.push(`**Definition:** ${v.definition}`);
    if (v.exampleSentence) lines.push(`**Example:** *${v.exampleSentence}*`);
    if (v.polishTranslation) lines.push(`**Polish:** ${v.polishTranslation}`);
    if (v.cefrLevel) lines.push(`**CEFR:** ${v.cefrLevel}`);
    lines.push("");
  }
  return lines.join("\n");
}

function generateGamesIndex(gameList: Record<string, unknown>[]): string {
  const lines = [
    "# Interactive Games",
    "",
    "Share these links with your students — no login required!",
    "",
    "| Game Type | Share Link | Plays |",
    "|-----------|-----------|-------|",
  ];
  for (const g of gameList) {
    const link = g.shareToken ? `/game/${g.shareToken}` : "—";
    lines.push(`| ${g.type} | ${link} | ${g.plays || 0} |`);
  }
  lines.push("\n> **Note:** Links are relative to your EduFactory domain.");
  return lines.join("\n");
}

function generateMarketplaceCard(project: Record<string, unknown>): string {
  const title = project.title || "English Teaching Pack";
  const level = project.cefrLevel || "B1";
  return `# Marketplace Product Card

## Product Title
**${title} — Complete English Teaching Pack (${level})**

## Short Description (for Etsy/TPT thumbnail)
Complete ${level} English lesson pack: worksheets, flashcards, games, lesson plan & more. Print-ready. Instant download.

## Tags
english teacher resources, ESL worksheets, ${level} english, teaching materials, lesson plan, flashcards, vocabulary activities, digital download, printable

## Price Suggestion
- Single pack: $4.99–$7.99
- Bundle (5 packs): $19.99
- Subscription: $9.99/month

## What's Included
- ✅ Worksheet (reading comprehension + exercises)
- ✅ Vocabulary list with definitions
- ✅ Flashcard set (print & cut)
- ✅ Grammar guide
- ✅ Lesson plan (60 min)
- ✅ Writing exercises
- ✅ Listening comprehension tasks
- ✅ Discussion questions
- ✅ Homework assignment
- ✅ Teacher notes
- ✅ 6 interactive online games (shareable links)

## License
For single classroom use. Not for redistribution.
`;
}

function generateEtsyListing(project: Record<string, unknown>): string {
  const title = project.title || "English Teaching Pack";
  const level = project.cefrLevel || "B1";
  return `ETSY LISTING
============

TITLE:
${title} | Complete ${level} English Lesson Pack | ESL Worksheets + Games + Lesson Plan | Instant Download

DESCRIPTION:
⭐ SAVE HOURS OF LESSON PLANNING! ⭐

This complete ${level} English teaching pack includes everything you need for a full lesson on "${title}".

✅ WHAT'S INCLUDED:
• Worksheet with reading comprehension & gap-fill exercises
• Vocabulary list (with definitions, examples & Polish translations)
• Printable flashcard set
• Grammar guide with explanations & practice
• Full 60-minute lesson plan
• Writing exercise prompts
• Listening comprehension tasks
• Discussion questions & speaking activities
• Homework assignment
• Teacher notes & differentiation tips
• 6 interactive online games (shareable links for students)

📥 INSTANT DOWNLOAD — PDF format, print-ready A4

🎯 LEVEL: ${level} | TOPIC: ${title}

Perfect for:
→ Private English tutors
→ Language school teachers
→ Primary & secondary school EFL teachers
→ Online English teachers

TAGS:
esl worksheet, english lesson plan,→ ${String(level).toLowerCase()} english,teaching resources, efl materials, printable flashcards, vocabulary activities, english games, lesson pack, instant download

PRICE: $5.99
CATEGORY: Craft Supplies & Tools > Educational Supplies
`;
}

function generateTPTDescription(project: Record<string, unknown>): string {
  const title = project.title || "English Teaching Pack";
  const level = project.cefrLevel || "B1";
  return `TEACHERS PAY TEACHERS (TPT) LISTING
=====================================

PRODUCT TITLE:
${title} | ${level} ESL Complete Lesson Bundle | Worksheets, Games, Lesson Plan

PRODUCT DESCRIPTION:
Save time and engage your students with this complete ${level} English lesson bundle based on "${title}".

This resource includes 10+ ready-to-use materials:
★ Worksheet (comprehension + gap-fill + true/false)
★ Vocabulary list with definitions & example sentences
★ Printable flashcard set
★ Grammar guide with practice exercises
★ Full lesson plan (60 minutes, with timing & objectives)
★ Writing prompts
★ Listening comprehension worksheet
★ Speaking/discussion question cards
★ Homework assignment
★ Teacher notes with differentiation strategies
★ 6 interactive digital games (quiz, memory, matching, fill-blanks, spelling, scramble)

GRADE LEVELS: 6-12, Adult Education
SUBJECT: English Language Arts, EFL/ESL
RESOURCE TYPE: Lesson, Activities, Printables, Digital
FILE TYPE: PDF + Links

STANDARDS: CEFR ${level}
PRICE: $5.00
`;
}
